// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1611652568);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1611652688);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1613040784);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1611652448);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1611652808);
user_pref("browser.cache.disk.capacity", 296960);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.search.region", "HK");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.lastModified", "Fri, 22 Jan 2021 23:33:01 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1611652568);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20200629235513");
user_pref("extensions.lastAppVersion", "68.10.0");
user_pref("extensions.lastPlatformVersion", "68.10.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"wetransfer@extensions.thunderbird.net\":\"89f18a36-b6a7-497e-89f1-022fbf2da4a3\",\"default-theme@mozilla.org\":\"90dfc83a-7991-4c2d-9e0b-00c4aed96d4d\",\"google@search.mozilla.org\":\"c5a7d0c1-a0c6-4584-9a38-f5a63e756281\",\"amazondotcom@search.mozilla.org\":\"33dd4e18-c884-48e7-8055-d5674b7356d5\",\"bing@search.mozilla.org\":\"a2ae6f4f-dd1c-4992-b789-076d43f7c00a\",\"ddg@search.mozilla.org\":\"d7b1141e-123e-4bcb-95b9-3016903c7d22\",\"twitter@search.mozilla.org\":\"f6b67c83-884f-4f2d-a715-a66d7f57f570\",\"wikipedia@search.mozilla.org\":\"7aa53621-85fc-4d77-928a-d7b6c222a72d\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("idle.lastDailyNotification", 1611652943);
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.append_preconfig_smtpservers.version", 2);
user_pref("mail.default_charsets.migrated", 1);
user_pref("mail.ui-rdf.version", 17);
user_pref("mailnews.database.global.datastore.id", "6cb05fee-a8e3-4aad-81ff-adcfe74dffe");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "68.10.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("places.database.lastMaintenance", 1611652943);
user_pref("places.history.expiration.transient_current_max_pages", 71599);
user_pref("security.sandbox.plugin.tempDirSuffix", "5d3ba845-1326-4d8b-88db-3ca8978e03d4");
user_pref("services.blocklist.pinning.checked", 1611652472);
user_pref("services.settings.clock_skew_seconds", -25);
user_pref("services.settings.last_etag", "\"1611647871515\"");
user_pref("services.settings.last_update_seconds", 1611652472);
user_pref("services.settings.main.hijack-blocklists.last_check", 1611652472);
user_pref("services.settings.main.language-dictionaries.last_check", 1611652472);
user_pref("services.settings.main.sites-classification.last_check", 1611652472);
user_pref("services.settings.security.onecrl.checked", 1611652472);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1611652943);
user_pref("toolkit.telemetry.cachedClientID", "fd73d92c-2e05-406e-9966-40c5d2d83716");
user_pref("toolkit.telemetry.prompted", 2);
